### ISSUE TITLE
Sidebar opt-in form changes

### ISSUE THREAD

**Issue by Ashishr2** [NepCoders/BlogTheme#12]
![optin-sidebar](https://cloud.githubusercontent.com/assets/14211914/11708083/98faf22e-9f33-11e5-9e50-826b7b1d9d97.jpg)

Background color #f1f1f1
Input form backgrounf #ffffff
button width 100%

**Comment by Ashishr2** [comment]
"Enter your email address below to subscribe our newsletter."

color #292929

**Comment by rajjora18** [comment]
Done
