### ISSUE TITLE
Widget changes

### ISSUE THREAD

**Issue by Ashishr2** [NepCoders/BlogTheme#13]
widget class bottom-margin:48px

**Comment by rajjora18** [comment]
Done

**Comment by Ashishr2** [comment]
check again

**Comment by Ashishr2** [comment]
![widget-title](https://cloud.githubusercontent.com/assets/14211914/12001659/1f788bf8-ab15-11e5-95e4-a6ba2ee569b8.jpg)

font-family:"Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif!important
font-weight:700

**Comment by Ashishr2** [comment]
font-family:'Oswald', sans-serif
letter-spacing:.5px
