### ISSUE TITLE
Header shadow not consitent

### ISSUE THREAD

**Issue by Ashishr2** [NepCoders/BlogTheme#22]
![header-shadow](https://cloud.githubusercontent.com/assets/14211914/11773155/cef80cb4-a24d-11e5-95ec-d75d0b4af029.jpg)

Apply the shadow to a common class/ID or parent container

**Comment by rajjora18** [comment]
Changed with the consistent  box-shadow: 0px 1px 5px rgba(0,0,0,0.1);

**Comment by Ashishr2** [comment]
check again
