### ISSUE TITLE
single post side in design

### ISSUE THREAD

**Issue by Ashishr2** [NepCoders/BlogTheme#73]
![you-may-also](https://cloud.githubusercontent.com/assets/14211914/11926116/41e23d48-a7ea-11e5-8d4a-3229977378d6.jpg)

**Comment by Ashishr2** [comment]
give shadow around the box

**Comment by Ashishr2** [comment]
![u](https://cloud.githubusercontent.com/assets/14211914/11993361/1a50c22a-aa58-11e5-8ef8-cabb81cccb4b.jpg) 

make the height of the image cover the box

**Comment by Ashishr2** [comment]
image is distorted

**Comment by jhalendra** [comment]
![slidein](https://cloud.githubusercontent.com/assets/7992766/12046616/4c10718a-aee4-11e5-9a01-33f377aaa5ab.png)
